package View;

import Conection.ConnectionCaminhao;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kkaro
 */
public class InterfaceCaminhão extends javax.swing.JFrame {
    private ConnectionCaminhao conexaoCam; 
    private ArrayList<String> lixeiras;
    private String identificador;
    /**
     * Creates new form InterfaceCaminhão
     */
    public InterfaceCaminhão() {
        initComponents();
        //estabelecerConexao();
//        lixeiras = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_mprota = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_lAtual = new javax.swing.JLabel();
        lbl_lProx = new javax.swing.JLabel();
        jb_solic = new javax.swing.JButton();
        jb_coletada = new javax.swing.JButton();
        jb_finali = new javax.swing.JButton();
        jb_cadastro = new javax.swing.JButton();
        jb_quebrar = new javax.swing.JButton();
        jb_concertar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIpServer = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPorta = new javax.swing.JTextPane();
        jbConectar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MAPA DE ROTA:");

        lbl_mprota.setText("...");

        jLabel7.setText("LIXEIRA ATUAL:");

        jLabel8.setText("PRÓXIMA LIXEIRA:");

        lbl_lAtual.setText("...");

        lbl_lProx.setText("...");

        jb_solic.setText("SOLICITAR ROTA");
        jb_solic.setEnabled(false);
        jb_solic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_solicActionPerformed(evt);
            }
        });

        jb_coletada.setText("LIXEIRA TAL COLETADA");
        jb_coletada.setEnabled(false);
        jb_coletada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_coletadaActionPerformed(evt);
            }
        });

        jb_finali.setText("ROTA FINALIZADA");
        jb_finali.setEnabled(false);
        jb_finali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_finaliActionPerformed(evt);
            }
        });

        jb_cadastro.setText("CADASTRAR CAMINHAO");
        jb_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cadastroActionPerformed(evt);
            }
        });

        jb_quebrar.setText("QUEBRAR CAMINHÃO");
        jb_quebrar.setEnabled(false);
        jb_quebrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_quebrarActionPerformed(evt);
            }
        });

        jb_concertar.setText("CONCERTAR CAMINHÃO");
        jb_concertar.setEnabled(false);
        jb_concertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_concertarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("IP:");

        txtIpServer.setText("127.0.0.1");
        jScrollPane2.setViewportView(txtIpServer);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("PORTA:");

        txtPorta.setText("1234");
        jScrollPane3.setViewportView(txtPorta);

        jbConectar.setText("CONECTAR");
        jbConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConectarActionPerformed(evt);
            }
        });

        jLabel4.setText("INFORMAÇÕES SOBRE A COLETA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_lAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_lProx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_mprota))
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jb_coletada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jb_finali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jb_quebrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jb_concertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jb_solic, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(jb_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbConectar)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_mprota, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_lAtual))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_lProx))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_solic)
                    .addComponent(jb_cadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_coletada)
                .addGap(7, 7, 7)
                .addComponent(jb_finali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_quebrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_concertar)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_solicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_solicActionPerformed
        try {
            // TODO add your handling code here:
            String rspt = conexaoCam.solicitarRota(identificador);
            System.out.println(rspt);
            String array[] = rspt.split(":");//IGNORANDO DIVISOR DA MENSAGEM
            for(int i=0;i<array.length;i++){//PERCORRENDO LIXERIAS E SALVANDO EM UM NOVO ARRAY
                lixeiras.add(array[i]);
            }  
            lbl_mprota.setText(array.toString());//SETANDO NA TELA LIXEIRAS DA ROTA
            atualizarRota();
            
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(InterfaceCaminhão.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_solicActionPerformed
    
    private void atualizarRota(){
        lbl_lAtual.setText(lixeiras.get(0));//SETANDO LIXEIRA ATUAL
        lbl_lProx.setText(lixeiras.get(1));//SETANDO PRÓXIMA LIXEIRA A SER RECOLHIDA
    }
    
    private void jb_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cadastroActionPerformed
        identificador = JOptionPane.showInputDialog("Defina o Identificador do caminhão:");
        System.out.println(identificador);
        
        try {
            String resp = conexaoCam.cadCaminhao(identificador);
            JOptionPane.showMessageDialog(null, resp);
            jb_coletada.setEnabled(true);
            jb_finali.setEnabled(true);
            jb_solic.setEnabled(true);
            jb_concertar.setEnabled(true);
            jb_quebrar.setEnabled(true);
            jb_cadastro.setEnabled(false);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o servidor!!");
        }
    }//GEN-LAST:event_jb_cadastroActionPerformed

    private void jb_coletadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_coletadaActionPerformed
        try {
            // TODO add your handling code here:
            String respt = conexaoCam.lixeiraColetada(lixeiras.get(0));
            lixeiras.remove(0);
            atualizarRota();
                    
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(InterfaceCaminhão.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_coletadaActionPerformed

    private void jb_finaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_finaliActionPerformed
        try {
            // TODO add your handling code here:
            String respt = conexaoCam.rotaFinalizada(identificador);
            
            lbl_mprota.setText("");
            lbl_lAtual.setText("");
            lbl_lProx.setText("");            
            
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(InterfaceCaminhão.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jb_finaliActionPerformed

    private void jb_quebrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_quebrarActionPerformed
        try {
            // TODO add your handling code here:
            conexaoCam.quebrar(identificador);            
            
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(InterfaceCaminhão.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jb_quebrarActionPerformed

    private void jb_concertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_concertarActionPerformed
        try {
            // TODO add your handling code here:
            conexaoCam.concertar(identificador);
            
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(InterfaceCaminhão.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jb_concertarActionPerformed

    private void jbConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConectarActionPerformed
        estabelecerConexao();
        lixeiras = new ArrayList<>();
    }//GEN-LAST:event_jbConectarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCaminhão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCaminhão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCaminhão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCaminhão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCaminhão().setVisible(true);
            }
        });
    }
    public void estabelecerConexao(){
        try {
            conexaoCam = new ConnectionCaminhao(txtIpServer.getText(), txtPorta.getText());
            System.out.println(conexaoCam.conecta());//ESTABELER A CONEXÃO
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(InterfaceCaminhão.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    
    
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbConectar;
    private javax.swing.JButton jb_cadastro;
    private javax.swing.JButton jb_coletada;
    private javax.swing.JButton jb_concertar;
    private javax.swing.JButton jb_finali;
    private javax.swing.JButton jb_quebrar;
    private javax.swing.JButton jb_solic;
    private javax.swing.JLabel lbl_lAtual;
    private javax.swing.JLabel lbl_lProx;
    private javax.swing.JLabel lbl_mprota;
    private javax.swing.JTextPane txtIpServer;
    private javax.swing.JTextPane txtPorta;
    // End of variables declaration//GEN-END:variables
}
